version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.19-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend:/work
      - /etc/letsencrypt/live/more-clothing.site:/etc/letsencrypt/live/more-clothing.site
      - /etc/letsencrypt/archive/more-clothing.site:/etc/letsencrypt/archive/more-clothing.site

      # 本番環境
      # - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

      # 開発環境
      - ./infra/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
