FROM mysql/mysql-server:8.0

ENV MYSQL_DATABASE=moreclo_db \
  MYSQL_USER=moreclothing \
	MYSQL_PASSWORD='.ht,Z&CJX*.dvh%Uxnrkmhw7u8ABJuvqSKf' \
	MYSQL_ROOT_PASSWORD='.ht,Z&CJX*.dvh%Uxnrkmhw7u8ABJuvqSKf' \
  TZ=Asia/Tokyo

COPY ./my.cnf /etc/my.cnf
RUN chmod 644 /etc/my.cnf